// <auto-generated />
using System;
using Listenarr.Plugins.Player.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Listenarr.Plugins.Player.Migrations
{
    [DbContext(typeof(PlayerDbContext))]
    partial class PlayerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Listenarr.Plugins.Player.Data.PlayerBookmark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AudiobookId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("FileIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .HasColumnType("TEXT");

                    b.Property<double>("PositionSeconds")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("AudiobookId");

                    b.ToTable("PlayerBookmarks", (string)null);
                });

            modelBuilder.Entity("Listenarr.Plugins.Player.Data.PlayerChapterCache", b =>
                {
                    b.Property<int>("AudiobookFileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChaptersJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AudiobookFileId");

                    b.ToTable("PlayerChapterCaches", (string)null);
                });

            modelBuilder.Entity("Listenarr.Plugins.Player.Data.PlayerPlaybackState", b =>
                {
                    b.Property<int>("AudiobookId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FileIndex")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Finished")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PositionSeconds")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("AudiobookId");

                    b.HasIndex("UpdatedUtc");

                    b.ToTable("PlayerPlaybackStates", (string)null);
                });

            modelBuilder.Entity("Listenarr.Plugins.Player.Data.PlayerSettings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoUnmonitorOnFinish")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PlayerSettings", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
